### ISSUE TITLE
Rationale behind iteration context and the stream method

### ISSUE THREAD

**Issue by andersea** [vxgmichel/aiostream#12]
Can you explain why this is needed? I tried iterating the stream directly and it seems to work, although I get a warning.

Having to get a context before you can iterate the stream seems like a lot of extra work. I am not getting the point of why this extra step is required.

**Comment by vxgmichel** [comment]
Thanks for creating this issue, maybe it's something that should be better documented. 

Consider the following asynchronous generator:
```python
async def count_to_ten():
    try:
        for i in range(10):
            yield i
            await asyncio.sleep(1)
    finally:
        print('cleaning up')
```
Now, say you're only interested by the first three values:
```python
async def main():
    xs = stream.enumerate(agen())
    async for i, x in xs:
        if i == 3:
            break
        print(x)
    print('done!')
```

And you run the main coroutine using the standard boiler-plate code:

```python
if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
```

Let's check the output:

```
[...]: UserWarning: AsyncIteratorContext is iterated outside of its context
  "AsyncIteratorContext is iterated outside of its context")
0
1
2
done!
```
And that's it, no clean up! According to [PEP 525](https://www.python.org/dev/peps/pep-0525/#asyncio), that's because you're actually supposed to add the following line before closing the loop:
```python
loop.run_until_complete(loop.shutdown_asyncgens())
```
Notice however that `'cleaning up'` will appear after `'done!'` which is usually not what you want. By using the stream method, the clean up gets to run before leaving the corresponding context:
```python
async def main():
    xs = stream.enumerate(agen())
    async with xs.stream() as streamer:
        async for i, x in streamer:
            if i == 3:
                break
            print(x)
    print('done!')
```
Note that if you use `await` instead of the asynchronous iteration, the streaming context is not necessary:
```python
async def main():
    xs = stream.iterate(agen())
    print(await xs[:3])
    print('done!')
```
Now if you can think of a more intuitive interface, I'd be happy to look into it!

**Comment by andersea** [comment]
Looks like I stepped into a minefield here.

https://github.com/dabeaz/curio/issues/176

https://vorpus.org/blog/some-thoughts-on-asynchronous-api-design-in-a-post-asyncawait-world/

This is actually broken in python IMHO.. If DB can't come up with any good solution, I am not even going to try. Closing.
