### ISSUE TITLE
use `operator` on a class method fails

### ISSUE THREAD

**Issue by jenda1** [vxgmichel/aiostream#23]
I tried to use `aiostream.core.operator` on a class method:

```python
from aiostream.core import operator

class test(object):
    @operator
    async def testit(self):
        pass

```

but it fails with error:

```console
$ python3.7 test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    class test(object):
  File "test.py", line 4, in test
    @operator
  File "/home/jlana/Dropbox/vyuka2/venv/lib/python3.7/site-packages/aiostream/core.py", line 333, in operator
    return decorator if func is None else decorator(func)
  File "/home/jlana/Dropbox/vyuka2/venv/lib/python3.7/site-packages/aiostream/core.py", line 279, in decorator
    init.__signature__ = signature.replace(parameters=new_parameters)
  File "/usr/lib/python3.7/inspect.py", line 2843, in replace
    return_annotation=return_annotation)
  File "/usr/lib/python3.7/inspect.py", line 2788, in __init__
    raise ValueError(msg)
ValueError: duplicate parameter name: 'self'
```

As workaround it is possible to use different name and call the operator with the class instance:

```python
class test(object):
    n = 123

    @operator
    async def testit(myself):
        yield myself.n

async def main():
    t = test()
    await stream.print(t.testit(t))

```

**Comment by vxgmichel** [comment]
Hi @jenda1, thank you for creating this issue.

The problem here is that the decorated generator becomes a `Stream` subclass, in order to provide support for pipe-lining (`|`), slicing (`[]`) and concatenation (`+`). That means `testit` is **not** a method and this is why you have to pass the `t` instance explicitly in your workaround.

Instead, you could consider this alternative:
```python
@operator
async def stream_from_test_instance(test):
    yield test.n


class test:
    n = 123

    def testit(self):
        return stream_from_test_instance(self)
```

Or, since streams are reusable:

```python
class test:

    def __init__(self, n):
        self.n = n
        self.stream = stream_from_test_instance(self)

    def testit(self):
        return self.stream
```

The error message you got isn't really explaining what's happening though. I think I'll try to detect `self` or `cls` arguments and raise an exception with a proper explanation.

Hope that helps, thanks again.

**Comment by vxgmichel** [comment]
> Let's try to detect self or cls arguments and raise an exception with a proper explanation.

Done ! (see PR #24.)
