### ISSUE TITLE
Have a better exception than AttributeError when a stream is used as a context

### ISSUE THREAD

**Issue by jonathon-love** [vxgmichel/aiostream#40]
hi i can use enumerate() improperly and it works as expected, i.e.:

```
async for i, r in enumerate(analysis.results):
    print(r)
```

but of course i get the `UserWarning: AsyncIteratorContext is iterated outside of its context`

but when i try and do it properly:

```
async with enumerate(analysis.results) as s:
    async for i, r in s:
        print(r)
```

i get an `AttributeError: __aexit__` on the `with` line.

i assume this is a bug (or am i misunderstanding something)?

with thanks

**Comment by vxgmichel** [comment]
Hi @jonathon-love, sorry for the late reply!

The issue here is that you forgot to use the [stream](https://aiostream.readthedocs.io/en/latest/core.html#aiostream.core.Stream.stream) method:

```python
async with enumerate(analysis.results).stream() as s:
    async for i, r in s:
        print(r)
```

I know it is a bit confusing, but streams can be iterated multiple times so a new streamer object has to be created for each usage. I think we need at least a better exception message than `AttributeError: __aexit__` so people don't get too confused about it. I'll rename the issue.

Thanks for the report!

**Comment by jonathon-love** [comment]
ah! my bad!

thanks for the response.

**Comment by vxgmichel** [comment]
Fixed! Thanks again for the report @jonathon-love
